# -*- auto-fill-function: nil; eval: (add-hook 'after-save-hook 'org-babel-tangle nil t); -*-

* Introduction
In this project, I am going to build a basic recipe website.

After completing this project I expect to have improved both my HTML and Git skills.

I'll experiment with a new approach in this project, where I plan everything ahead, and only then start programming.

But first let's get the setup done.

** Setup

#+begin_quote
1. Create a new repo for this project on GitHub.com and call it odin-recipes and choose the public option instead of the default private.

2. Clone that repository onto your local machine, inside the repos folder that you previously created in the Git Basics lesson. The command should look like git clone git@github.com:username/odin-recipes.git (use SSH).

3. Now cd into the odin-recipes project directory that is now on your local machine.

4. Set up your README.md file and write a brief introduction describing what the current project is and what skills you will have demonstrated once you have completed it. (You can also do this as a self-reflection at the end of the project, which is a good way to review what you have learned.)
#+end_quote

** Plan

I believe the first thing to do would be to outline the project files and their roles.

- [D] odin-recipes
  - index.html
    - links to recipes (unordered list)
  - [D] recipes
    - recipe1.html
      - image (free)
      - description
      - ingredients (ul)
      - steps (ol)
    - recipe2.html
    - recipe3.html


The plan: do it in the order of the assignment.
I'll be able to reuse the scaffold of the trickiest part, the recipe page.

** Work

*** Homepage
This is the homepage of the website.
It will contain a nice header and links to three recipes.

[[file:index.html][index.html]] ≡

#+begin_src html :tangle index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>My first page from Odin</title>
  </head>

  <body>
    <h1>Odin Recipes</h1>
  </body>
</html>
#+end_src

*** Recipes
These are the three recipes of the website.

